/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as CartesRouteImport } from './routes/cartes'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as FonctionnementRouteImport } from './routes/fonctionnement'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as RemboursementRouteImport } from './routes/remboursement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const CartesRoute = CartesRouteImport.update({
  id: '/cartes',
  path: '/cartes',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnementRoute = FonctionnementRouteImport.update({
  id: '/fonctionnement',
  path: '/fonctionnement',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const RemboursementRoute = RemboursementRouteImport.update({
  id: '/remboursement',
  path: '/remboursement',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/cartes': typeof CartesRoute
  '/dossier': typeof DossierRoute
  '/fonctionnement': typeof FonctionnementRoute
  '/legal': typeof LegalRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/remboursement': typeof RemboursementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/cartes': typeof CartesRoute
  '/dossier': typeof DossierRoute
  '/fonctionnement': typeof FonctionnementRoute
  '/legal': typeof LegalRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/remboursement': typeof RemboursementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/cartes': typeof CartesRoute
  '/dossier': typeof DossierRoute
  '/fonctionnement': typeof FonctionnementRoute
  '/legal': typeof LegalRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/remboursement': typeof RemboursementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avis'
    | '/cartes'
    | '/dossier'
    | '/fonctionnement'
    | '/legal'
    | '/paiement'
    | '/panier'
    | '/remboursement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avis'
    | '/cartes'
    | '/dossier'
    | '/fonctionnement'
    | '/legal'
    | '/paiement'
    | '/panier'
    | '/remboursement'
  id:
    | '__root__'
    | '/'
    | '/avis'
    | '/cartes'
    | '/dossier'
    | '/fonctionnement'
    | '/legal'
    | '/paiement'
    | '/panier'
    | '/remboursement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisRoute: typeof AvisRoute
  CartesRoute: typeof CartesRoute
  DossierRoute: typeof DossierRoute
  FonctionnementRoute: typeof FonctionnementRoute
  LegalRoute: typeof LegalRoute
  PaiementRoute: typeof PaiementRoute
  PanierRoute: typeof PanierRoute
  RemboursementRoute: typeof RemboursementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartes': {
      id: '/cartes'
      path: '/cartes'
      fullPath: '/cartes'
      preLoaderRoute: typeof CartesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnement': {
      id: '/fonctionnement'
      path: '/fonctionnement'
      fullPath: '/fonctionnement'
      preLoaderRoute: typeof FonctionnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remboursement': {
      id: '/remboursement'
      path: '/remboursement'
      fullPath: '/remboursement'
      preLoaderRoute: typeof RemboursementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisRoute: AvisRoute,
  CartesRoute: CartesRoute,
  DossierRoute: DossierRoute,
  FonctionnementRoute: FonctionnementRoute,
  LegalRoute: LegalRoute,
  PaiementRoute: PaiementRoute,
  PanierRoute: PanierRoute,
  RemboursementRoute: RemboursementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../../Users/Emma Atb/Downloads/service-k917-official-main/src/router.tsx'
import type { startInstance } from '../../Users/Emma Atb/Downloads/service-k917-official-main/src/start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
